// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

#include <string>

namespace client {

struct Reply;
struct User;

class ClientInterface {
public:
    virtual ~ClientInterface() {}

    /**    static create_with_path(path: string): client_interface; */
    virtual User get_userinfo(const std::string & username) = 0;

    virtual Reply register_account(const std::string & username, const std::string & password, const std::string & deviceid) = 0;

    virtual Reply check_auth(const std::string & username, const std::string & auth) = 0;

    virtual Reply login(const std::string & username, const std::string & password, const std::string & deviceid) = 0;
};

}  // namespace client
