// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace client {

struct User;

class Client {
public:
    virtual ~Client() {}

    static std::shared_ptr<Client> create_with_path(const std::string & path);

    virtual std::vector<User> get_userinfo() = 0;

    virtual void register(const std::string & username, const std::string & password, const std::string & deviceid) = 0;

    virtual void check_auth(const std::string & username, const std::string & auth) = 0;

    virtual void login(const std::string & username, const std::string & password, const std::string & deviceid) = 0;
};

}  // namespace client
