// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace client {

struct User final {
    int32_t id;
    std::string username;
    std::string password;
    std::string auth;
    std::string deviceid;

    User(int32_t id_,
         std::string username_,
         std::string password_,
         std::string auth_,
         std::string deviceid_)
    : id(std::move(id_))
    , username(std::move(username_))
    , password(std::move(password_))
    , auth(std::move(auth_))
    , deviceid(std::move(deviceid_))
    {}
};

}  // namespace client
