// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#include "NativeReplyStruct.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeReplyStruct::NativeReplyStruct() = default;

NativeReplyStruct::~NativeReplyStruct() = default;

auto NativeReplyStruct::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeReplyStruct>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.resultcode)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.resultmsg)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.isauthvalid)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.auth)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeReplyStruct::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeReplyStruct>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mResultcode)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mResultmsg)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mIsauthvalid)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAuth))};
}

}  // namespace djinni_generated
