// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#include "NativeUserStruct.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeUserStruct::NativeUserStruct() = default;

NativeUserStruct::~NativeUserStruct() = default;

auto NativeUserStruct::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeUserStruct>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.username)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.password)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.auth)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.deviceid)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeUserStruct::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeUserStruct>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUsername)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPassword)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAuth)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mDeviceid))};
}

}  // namespace djinni_generated
