// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#include "NativeClientInterface.hpp"  // my header
#include "Marshal.hpp"
#include "NativeReply.hpp"
#include "NativeUser.hpp"

namespace djinni_generated {

NativeClientInterface::NativeClientInterface() : ::djinni::JniInterface<::client::ClientInterface, NativeClientInterface>("com/mycompany/client/ClientInterface$CppProxy") {}

NativeClientInterface::~NativeClientInterface() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_client_ClientInterface_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::client::ClientInterface>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_client_ClientInterface_createWithPath(JNIEnv* jniEnv, jobject /*this*/, jstring j_path)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::client::ClientInterface::create_with_path(::djinni::String::toCpp(jniEnv, j_path));
        return ::djinni::release(::djinni_generated::NativeClientInterface::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_client_ClientInterface_00024CppProxy_native_1getUserinfo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_username)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::client::ClientInterface>(nativeRef);
        auto r = ref->get_userinfo(::djinni::String::toCpp(jniEnv, j_username));
        return ::djinni::release(::djinni_generated::NativeUser::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_client_ClientInterface_00024CppProxy_native_1registerAccount(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_username, jstring j_password, jstring j_deviceid)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::client::ClientInterface>(nativeRef);
        auto r = ref->register_account(::djinni::String::toCpp(jniEnv, j_username),
                                       ::djinni::String::toCpp(jniEnv, j_password),
                                       ::djinni::String::toCpp(jniEnv, j_deviceid));
        return ::djinni::release(::djinni_generated::NativeReply::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_client_ClientInterface_00024CppProxy_native_1checkAuth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_username, jstring j_auth)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::client::ClientInterface>(nativeRef);
        auto r = ref->check_auth(::djinni::String::toCpp(jniEnv, j_username),
                                 ::djinni::String::toCpp(jniEnv, j_auth));
        return ::djinni::release(::djinni_generated::NativeReply::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_client_ClientInterface_00024CppProxy_native_1login(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_username, jstring j_password, jstring j_deviceid)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::client::ClientInterface>(nativeRef);
        auto r = ref->login(::djinni::String::toCpp(jniEnv, j_username),
                            ::djinni::String::toCpp(jniEnv, j_password),
                            ::djinni::String::toCpp(jniEnv, j_deviceid));
        return ::djinni::release(::djinni_generated::NativeReply::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
