// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAUser.h"
#import <Foundation/Foundation.h>
@class TDAClient;


@interface TDAClient : NSObject

+ (nullable TDAClient *)createWithPath:(nonnull NSString *)path;

- (nonnull NSArray<TDAUser *> *)getUserinfo;

- (void)register:(nonnull NSString *)username
        password:(nonnull NSString *)password
        deviceid:(nonnull NSString *)deviceid;

- (void)checkAuth:(nonnull NSString *)username
             auth:(nonnull NSString *)auth;

- (void)login:(nonnull NSString *)username
     password:(nonnull NSString *)password
     deviceid:(nonnull NSString *)deviceid;

@end
