// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReply.h"
#import "TDAUser.h"
#import <Foundation/Foundation.h>


@interface TDAClientInterface : NSObject

/**    static create_with_path(path: string): client_interface; */
- (nonnull TDAUser *)getUserinfo:(nonnull NSString *)username;

- (nonnull TDAReply *)registerAccount:(nonnull NSString *)username
                             password:(nonnull NSString *)password
                             deviceid:(nonnull NSString *)deviceid;

- (nonnull TDAReply *)checkAuth:(nonnull NSString *)username
                           auth:(nonnull NSString *)auth;

- (nonnull TDAReply *)login:(nonnull NSString *)username
                   password:(nonnull NSString *)password
                   deviceid:(nonnull NSString *)deviceid;

@end
