// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReply.h"
#import "TDAUser.h"
#import <Foundation/Foundation.h>
@class TDAClient;


@interface TDAClient : NSObject

+ (nullable TDAClient *)createWithPath:(nonnull NSString *)path;

- (nonnull TDAUser *)getUserinfo:(nonnull NSString *)username;

- (nonnull TDAReply *)register:(nonnull NSString *)username
                      password:(nonnull NSString *)password
                      deviceid:(nonnull NSString *)deviceid;

- (nonnull TDAReply *)checkAuth:(nonnull NSString *)username
                           auth:(nonnull NSString *)auth;

- (nonnull TDAReply *)login:(nonnull NSString *)username
                   password:(nonnull NSString *)password
                   deviceid:(nonnull NSString *)deviceid;

@end
