// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAClientInterface+Private.h"
#import "TDAClientInterface.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "TDAReply+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TDAClientInterface ()

- (id)initWithCpp:(const std::shared_ptr<::client::ClientInterface>&)cppRef;

@end

@implementation TDAClientInterface {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::client::ClientInterface>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::client::ClientInterface>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull TDAReply *)registerAccount:(nonnull NSString *)username
                             password:(nonnull NSString *)password
                             deviceid:(nonnull NSString *)deviceid {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->register_account(::djinni::String::toCpp(username),
                                                                    ::djinni::String::toCpp(password),
                                                                    ::djinni::String::toCpp(deviceid));
        return ::djinni_generated::Reply::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull TDAReply *)checkAuth:(nonnull NSString *)username
                           auth:(nonnull NSString *)auth {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->check_auth(::djinni::String::toCpp(username),
                                                              ::djinni::String::toCpp(auth));
        return ::djinni_generated::Reply::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull TDAReply *)login:(nonnull NSString *)username
                   password:(nonnull NSString *)password
                   deviceid:(nonnull NSString *)deviceid {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->login(::djinni::String::toCpp(username),
                                                         ::djinni::String::toCpp(password),
                                                         ::djinni::String::toCpp(deviceid));
        return ::djinni_generated::Reply::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ClientInterface::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ClientInterface::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TDAClientInterface>(cpp);
}

}  // namespace djinni_generated

@end
