// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import <Foundation/Foundation.h>

@interface TDAReplyStruct : NSObject
- (nonnull instancetype)initWithResultcode:(int32_t)resultcode
                                 resultmsg:(nonnull NSString *)resultmsg
                               isauthvalid:(BOOL)isauthvalid
                                      auth:(nonnull NSString *)auth;
+ (nonnull instancetype)replyStructWithResultcode:(int32_t)resultcode
                                        resultmsg:(nonnull NSString *)resultmsg
                                      isauthvalid:(BOOL)isauthvalid
                                             auth:(nonnull NSString *)auth;

@property (nonatomic, readonly) int32_t resultcode;

@property (nonatomic, readonly, nonnull) NSString * resultmsg;

@property (nonatomic, readonly) BOOL isauthvalid;

@property (nonatomic, readonly, nonnull) NSString * auth;

@end
