// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReplyStruct.h"
#include "reply_struct.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TDAReplyStruct;

namespace djinni_generated {

struct ReplyStruct
{
    using CppType = ::client::ReplyStruct;
    using ObjcType = TDAReplyStruct*;

    using Boxed = ReplyStruct;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
