// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReply+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Reply::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.resultcode),
            ::djinni::String::toCpp(obj.resultmsg),
            ::djinni::Bool::toCpp(obj.isauthvalid),
            ::djinni::String::toCpp(obj.auth)};
}

auto Reply::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TDAReply alloc] initWithResultcode:(::djinni::I32::fromCpp(cpp.resultcode))
                                      resultmsg:(::djinni::String::fromCpp(cpp.resultmsg))
                                    isauthvalid:(::djinni::Bool::fromCpp(cpp.isauthvalid))
                                           auth:(::djinni::String::fromCpp(cpp.auth))];
}

}  // namespace djinni_generated
