// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReply.h"


@implementation TDAReply

- (nonnull instancetype)initWithResultcode:(int32_t)resultcode
                                 resultmsg:(nonnull NSString *)resultmsg
                               isauthvalid:(BOOL)isauthvalid
                                      auth:(nonnull NSString *)auth
{
    if (self = [super init]) {
        _resultcode = resultcode;
        _resultmsg = [resultmsg copy];
        _isauthvalid = isauthvalid;
        _auth = [auth copy];
    }
    return self;
}

+ (nonnull instancetype)replyWithResultcode:(int32_t)resultcode
                                  resultmsg:(nonnull NSString *)resultmsg
                                isauthvalid:(BOOL)isauthvalid
                                       auth:(nonnull NSString *)auth
{
    return [[self alloc] initWithResultcode:resultcode
                                  resultmsg:resultmsg
                                isauthvalid:isauthvalid
                                       auth:auth];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p resultcode:%@ resultmsg:%@ isauthvalid:%@ auth:%@>", self.class, (void *)self, @(self.resultcode), self.resultmsg, @(self.isauthvalid), self.auth];
}

@end
