// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAReply.h"
#include "reply.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TDAReply;

namespace djinni_generated {

struct Reply
{
    using CppType = ::client::Reply;
    using ObjcType = TDAReply*;

    using Boxed = Reply;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
