// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAUser.h"


@implementation TDAUser

- (nonnull instancetype)initWithId:(int32_t)id
                          username:(nonnull NSString *)username
                          password:(nonnull NSString *)password
                              auth:(int32_t)auth
                          deviceid:(nonnull NSString *)deviceid
{
    if (self = [super init]) {
        _id = id;
        _username = [username copy];
        _password = [password copy];
        _auth = auth;
        _deviceid = [deviceid copy];
    }
    return self;
}

+ (nonnull instancetype)userWithId:(int32_t)id
                          username:(nonnull NSString *)username
                          password:(nonnull NSString *)password
                              auth:(int32_t)auth
                          deviceid:(nonnull NSString *)deviceid
{
    return [[self alloc] initWithId:id
                           username:username
                           password:password
                               auth:auth
                           deviceid:deviceid];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ username:%@ password:%@ auth:%@ deviceid:%@>", self.class, (void *)self, @(self.id), self.username, self.password, @(self.auth), self.deviceid];
}

@end
