// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAUserStruct+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto UserStruct::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::String::toCpp(obj.username),
            ::djinni::String::toCpp(obj.password),
            ::djinni::String::toCpp(obj.auth),
            ::djinni::String::toCpp(obj.deviceid)};
}

auto UserStruct::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TDAUserStruct alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                    username:(::djinni::String::fromCpp(cpp.username))
                                    password:(::djinni::String::fromCpp(cpp.password))
                                        auth:(::djinni::String::fromCpp(cpp.auth))
                                    deviceid:(::djinni::String::fromCpp(cpp.deviceid))];
}

}  // namespace djinni_generated
