// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAUserStruct.h"
#include "user_struct.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TDAUserStruct;

namespace djinni_generated {

struct UserStruct
{
    using CppType = ::client::UserStruct;
    using ObjcType = TDAUserStruct*;

    using Boxed = UserStruct;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
