// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "TDAUser.h"
#include "user.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TDAUser;

namespace djinni_generated {

struct User
{
    using CppType = ::client::User;
    using ObjcType = TDAUser*;

    using Boxed = User;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
