// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: check_auth.proto

#include "check_auth.pb.h"
#include "check_auth.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace RegisterAndLogin {

static const char* CheckAuth_method_names[] = {
  "/RegisterAndLogin.CheckAuth/CheckAuth",
};

std::unique_ptr< CheckAuth::Stub> CheckAuth::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CheckAuth::Stub> stub(new CheckAuth::Stub(channel));
  return stub;
}

CheckAuth::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CheckAuth_(CheckAuth_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CheckAuth::Stub::CheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::RegisterAndLogin::CheckAuthReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CheckAuth_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>* CheckAuth::Stub::AsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::RegisterAndLogin::CheckAuthReply>::Create(channel_.get(), cq, rpcmethod_CheckAuth_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>* CheckAuth::Stub::PrepareAsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::RegisterAndLogin::CheckAuthReply>::Create(channel_.get(), cq, rpcmethod_CheckAuth_, context, request, false);
}

CheckAuth::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CheckAuth_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CheckAuth::Service, ::RegisterAndLogin::CheckAuthRequest, ::RegisterAndLogin::CheckAuthReply>(
          std::mem_fn(&CheckAuth::Service::CheckAuth), this)));
}

CheckAuth::Service::~Service() {
}

::grpc::Status CheckAuth::Service::CheckAuth(::grpc::ServerContext* context, const ::RegisterAndLogin::CheckAuthRequest* request, ::RegisterAndLogin::CheckAuthReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace RegisterAndLogin

