// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: check_auth.proto
#ifndef GRPC_check_5fauth_2eproto__INCLUDED
#define GRPC_check_5fauth_2eproto__INCLUDED

#include "check_auth.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace RegisterAndLogin {

// Service定义
class CheckAuth final {
 public:
  static constexpr char const* service_full_name() {
    return "RegisterAndLogin.CheckAuth";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::RegisterAndLogin::CheckAuthReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>> AsyncCheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>>(AsyncCheckAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>> PrepareAsyncCheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>>(PrepareAsyncCheckAuthRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>* AsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::CheckAuthReply>* PrepareAsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::RegisterAndLogin::CheckAuthReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>> AsyncCheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>>(AsyncCheckAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>> PrepareAsyncCheckAuth(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>>(PrepareAsyncCheckAuthRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>* AsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::CheckAuthReply>* PrepareAsyncCheckAuthRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckAuth_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::RegisterAndLogin::CheckAuthRequest* request, ::RegisterAndLogin::CheckAuthReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CheckAuth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::RegisterAndLogin::CheckAuthRequest* request, ::RegisterAndLogin::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAuth(::grpc::ServerContext* context, ::RegisterAndLogin::CheckAuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::RegisterAndLogin::CheckAuthReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckAuth<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CheckAuth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::RegisterAndLogin::CheckAuthRequest* request, ::RegisterAndLogin::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CheckAuth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::RegisterAndLogin::CheckAuthRequest, ::RegisterAndLogin::CheckAuthReply>(std::bind(&WithStreamedUnaryMethod_CheckAuth<BaseClass>::StreamedCheckAuth, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::RegisterAndLogin::CheckAuthRequest* request, ::RegisterAndLogin::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckAuth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RegisterAndLogin::CheckAuthRequest,::RegisterAndLogin::CheckAuthReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckAuth<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckAuth<Service > StreamedService;
};

}  // namespace RegisterAndLogin


#endif  // GRPC_check_5fauth_2eproto__INCLUDED
