// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto
#ifndef GRPC_client_2eproto__INCLUDED
#define GRPC_client_2eproto__INCLUDED

#include "client.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace client {

// Service定义
class Client final {
 public:
  static constexpr char const* service_full_name() {
    return "client.Client";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::client::CheckAuthReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>> AsyncCheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>>(AsyncCheckAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>> PrepareAsyncCheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>>(PrepareAsyncCheckAuthRaw(context, request, cq));
    }
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::client::LoginReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>> AsyncLogin(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    virtual ::grpc::Status Register(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::client::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>> AsyncRegister(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>* AsyncCheckAuthRaw(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::CheckAuthReply>* PrepareAsyncCheckAuthRaw(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>* AsyncLoginRaw(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::LoginReply>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::client::RegisterReply>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::client::CheckAuthReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>> AsyncCheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>>(AsyncCheckAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>> PrepareAsyncCheckAuth(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>>(PrepareAsyncCheckAuthRaw(context, request, cq));
    }
    ::grpc::Status Login(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::client::LoginReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::LoginReply>> AsyncLogin(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::LoginReply>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::LoginReply>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::LoginReply>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status Register(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::client::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>> AsyncRegister(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>>(PrepareAsyncRegisterRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>* AsyncCheckAuthRaw(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client::CheckAuthReply>* PrepareAsyncCheckAuthRaw(::grpc::ClientContext* context, const ::client::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client::LoginReply>* AsyncLoginRaw(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client::LoginReply>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::client::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::client::RegisterReply>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::client::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckAuth_;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_Register_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::client::CheckAuthRequest* request, ::client::CheckAuthReply* response);
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::client::LoginRequest* request, ::client::LoginReply* response);
    virtual ::grpc::Status Register(::grpc::ServerContext* context, const ::client::RegisterRequest* request, ::client::RegisterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CheckAuth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::client::CheckAuthRequest* request, ::client::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAuth(::grpc::ServerContext* context, ::client::CheckAuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::client::CheckAuthReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::client::LoginRequest* request, ::client::LoginReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::client::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::client::LoginReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Register() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::client::RegisterRequest* request, ::client::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::client::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::client::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckAuth<WithAsyncMethod_Login<WithAsyncMethod_Register<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CheckAuth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::client::CheckAuthRequest* request, ::client::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::client::LoginRequest* request, ::client::LoginReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Register() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::client::RegisterRequest* request, ::client::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckAuth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CheckAuth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::client::CheckAuthRequest, ::client::CheckAuthReply>(std::bind(&WithStreamedUnaryMethod_CheckAuth<BaseClass>::StreamedCheckAuth, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CheckAuth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckAuth(::grpc::ServerContext* context, const ::client::CheckAuthRequest* request, ::client::CheckAuthReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckAuth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::client::CheckAuthRequest,::client::CheckAuthReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::client::LoginRequest, ::client::LoginReply>(std::bind(&WithStreamedUnaryMethod_Login<BaseClass>::StreamedLogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::client::LoginRequest* request, ::client::LoginReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::client::LoginRequest,::client::LoginReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Register() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::client::RegisterRequest, ::client::RegisterReply>(std::bind(&WithStreamedUnaryMethod_Register<BaseClass>::StreamedRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::client::RegisterRequest* request, ::client::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::client::RegisterRequest,::client::RegisterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckAuth<WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_Register<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckAuth<WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_Register<Service > > > StreamedService;
};

}  // namespace client


#endif  // GRPC_client_2eproto__INCLUDED
