// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: register.proto
#ifndef GRPC_register_2eproto__INCLUDED
#define GRPC_register_2eproto__INCLUDED

#include "register.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace RegisterAndLogin {

// Service定义
class Register final {
 public:
  static constexpr char const* service_full_name() {
    return "RegisterAndLogin.Register";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Register(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::RegisterAndLogin::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>> AsyncRegister(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterAndLogin::RegisterReply>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Register(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::RegisterAndLogin::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>> AsyncRegister(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>>(PrepareAsyncRegisterRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterAndLogin::RegisterReply>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::RegisterAndLogin::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Register_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Register(::grpc::ServerContext* context, const ::RegisterAndLogin::RegisterRequest* request, ::RegisterAndLogin::RegisterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Register() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::RegisterAndLogin::RegisterRequest* request, ::RegisterAndLogin::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::RegisterAndLogin::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::RegisterAndLogin::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Register<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Register() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::RegisterAndLogin::RegisterRequest* request, ::RegisterAndLogin::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Register() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::RegisterAndLogin::RegisterRequest, ::RegisterAndLogin::RegisterReply>(std::bind(&WithStreamedUnaryMethod_Register<BaseClass>::StreamedRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::RegisterAndLogin::RegisterRequest* request, ::RegisterAndLogin::RegisterReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RegisterAndLogin::RegisterRequest,::RegisterAndLogin::RegisterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Register<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Register<Service > StreamedService;
};

}  // namespace RegisterAndLogin


#endif  // GRPC_register_2eproto__INCLUDED
