// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check_auth.proto

package io.grpc.registerandlogin;

public final class CheckAuthProto {
  private CheckAuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterAndLogin_CheckAuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterAndLogin_CheckAuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterAndLogin_CheckAuthReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterAndLogin_CheckAuthReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020check_auth.proto\022\020RegisterAndLogin\"2\n\020" +
      "CheckAuthRequest\022\020\n\010userName\030\001 \001(\t\022\014\n\004au" +
      "th\030\002 \001(\t\"!\n\016CheckAuthReply\022\017\n\007isValid\030\003 " +
      "\001(\0102`\n\tCheckAuth\022S\n\tCheckAuth\022\".Register" +
      "AndLogin.CheckAuthRequest\032 .RegisterAndL" +
      "ogin.CheckAuthReply\"\000B2\n\030io.grpc.registe" +
      "randloginB\016CheckAuthProtoP\001\242\002\003RALb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegisterAndLogin_CheckAuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterAndLogin_CheckAuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterAndLogin_CheckAuthRequest_descriptor,
        new java.lang.String[] { "UserName", "Auth", });
    internal_static_RegisterAndLogin_CheckAuthReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RegisterAndLogin_CheckAuthReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterAndLogin_CheckAuthReply_descriptor,
        new java.lang.String[] { "IsValid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
