// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package com.mycompany.client;

public final class Reply {


    /*package*/ final int mResultcode;

    /*package*/ final String mResultmsg;

    /*package*/ final boolean mIsauthvalid;

    /*package*/ final String mAuth;

    public Reply(
            int resultcode,
            String resultmsg,
            boolean isauthvalid,
            String auth) {
        this.mResultcode = resultcode;
        this.mResultmsg = resultmsg;
        this.mIsauthvalid = isauthvalid;
        this.mAuth = auth;
    }

    public int getResultcode() {
        return mResultcode;
    }

    public String getResultmsg() {
        return mResultmsg;
    }

    public boolean getIsauthvalid() {
        return mIsauthvalid;
    }

    public String getAuth() {
        return mAuth;
    }

    @Override
    public String toString() {
        return "Reply{" +
                "mResultcode=" + mResultcode +
                "," + "mResultmsg=" + mResultmsg +
                "," + "mIsauthvalid=" + mIsauthvalid +
                "," + "mAuth=" + mAuth +
        "}";
    }

}
