// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

package com.mycompany.client;

public final class User {


    /*package*/ final int mId;

    /*package*/ final String mUsername;

    /*package*/ final String mPassword;

    /*package*/ final int mAuth;

    /*package*/ final String mDeviceid;

    public User(
            int id,
            String username,
            String password,
            int auth,
            String deviceid) {
        this.mId = id;
        this.mUsername = username;
        this.mPassword = password;
        this.mAuth = auth;
        this.mDeviceid = deviceid;
    }

    public int getId() {
        return mId;
    }

    public String getUsername() {
        return mUsername;
    }

    public String getPassword() {
        return mPassword;
    }

    public int getAuth() {
        return mAuth;
    }

    public String getDeviceid() {
        return mDeviceid;
    }

    @Override
    public String toString() {
        return "User{" +
                "mId=" + mId +
                "," + "mUsername=" + mUsername +
                "," + "mPassword=" + mPassword +
                "," + "mAuth=" + mAuth +
                "," + "mDeviceid=" + mDeviceid +
        "}";
    }

}
